/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.PessoaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.Aluno;

/**
 *
 * @author estevao
 */
public class TelaAluno extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public TelaAluno() {
        initComponents();

    }
public void pesquisarAluno(String nome) throws ClassNotFoundException, SQLException{
    
    PessoaDAO dao = new PessoaDAO();
    
    DefaultTableModel modelo = (DefaultTableModel) tabelaAluno.getModel();
    
    modelo.setNumRows(0);
    tabelaAluno.getColumnModel().getColumn(0).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(1).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(2).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(3).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(4).setPreferredWidth(100);

     Aluno a = new Aluno();
     a = dao.BuscarAluno(nome);
{
	modelo.addRow(new Object[]{
            a.getNome(), 
            a.getRg(), 
            a.getCpf(), 
            a.getEndereco(), 
            a.getIra()});
	
}  
}
    
public void preencherTabela() throws ClassNotFoundException, SQLException{
    
    PessoaDAO dao = new PessoaDAO();
    
    DefaultTableModel modelo = (DefaultTableModel) tabelaAluno.getModel();
    
    modelo.setNumRows(0);
    tabelaAluno.getColumnModel().getColumn(0).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(1).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(2).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(3).setPreferredWidth(100);
    tabelaAluno.getColumnModel().getColumn(4).setPreferredWidth(100);

    for (Aluno a : dao.getAlunos()) {
	modelo.addRow(new Object[]{
            a.getNome(), 
            a.getRg(), 
            a.getCpf(), 
            a.getEndereco(), 
            a.getIra()});
	}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_AdicionaAluno = new javax.swing.JButton();
        btn_ExcluiAluno = new javax.swing.JButton();
        btn_PesquisaAluno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_CampoNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_AdicionaAluno.setText("Adicionar Aluno");
        btn_AdicionaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionaAlunoActionPerformed(evt);
            }
        });

        btn_ExcluiAluno.setText("Excluir");
        btn_ExcluiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluiAlunoActionPerformed(evt);
            }
        });

        btn_PesquisaAluno.setText("Pesquisar");
        btn_PesquisaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisaAlunoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Aluno:");

        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG", "CPF", "Endereço", "IRA"
            }
        ));
        jScrollPane1.setViewportView(tabelaAluno);

        jButton1.setText("Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btn_ExcluiAluno)
                        .addGap(100, 100, 100)
                        .addComponent(btn_PesquisaAluno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_AdicionaAluno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btn_AdicionaAluno)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ExcluiAluno)
                    .addComponent(btn_PesquisaAluno))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdicionaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionaAlunoActionPerformed
        // TODO add your handling code here:
        AdicionarAluno addaluno = new AdicionarAluno();
        addaluno.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_AdicionaAlunoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaPessoa principal = new TelaPessoa();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ExcluiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluiAlunoActionPerformed
        // TODO add your handling code here:
        PessoaDAO dao = new PessoaDAO();
        String nome = txt_CampoNome.getText();
        dao.excluirAluno(nome);
        txt_CampoNome.setText("");
        
    }//GEN-LAST:event_btn_ExcluiAlunoActionPerformed

    private void btn_PesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisaAlunoActionPerformed
        // TODO add your handling code here:
          String nome = txt_CampoNome.getText();
        if(nome.isEmpty()){
            try {
                preencherTabela();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
             try {
                 pesquisarAluno(nome);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_btn_PesquisaAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AdicionaAluno;
    private javax.swing.JButton btn_ExcluiAluno;
    private javax.swing.JButton btn_PesquisaAluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField txt_CampoNome;
    // End of variables declaration//GEN-END:variables
}
